:: 1v1
call RENAME_From_To.bat "[NMC] Plant Waste v2" "[RANK] Plant Waste ZH v2"
call RENAME_From_To.bat "Abandoned Farms ZH v1" "[RANK] Abandoned Farms ZH v1"
call RENAME_From_To.bat "Arab Tragedy ZHv3" "[RANK] A New Tradegy ZH v1"
call RENAME_From_To.bat "Battle Plan ZH v1" "[RANK] Battle Plan ZH v1"
call RENAME_From_To.bat "Blossoming Valley ZH v1" "[RANK] Blossoming Valley ZH v1"
call RENAME_From_To.bat "Combat-Island" "[RANK] Combat Island ZH v1"
call RENAME_From_To.bat "Down the Road ZH v1" "[RANK] Down the Road ZH v1"
call RENAME_From_To.bat "Drallim Desert v2" "[RANK] Drallim Desert ZH v2"
call RENAME_From_To.bat "Egyptian Oasis ZH v1" "[RANK] Egyptian Oasis ZH v1"
call RENAME_From_To.bat "Farmlands of the Fallen ZH v3" "[RANK] Farmlands of the Fallen ZH v1"
call RENAME_From_To.bat "Freezing Rain v2" "[RANK] Freezing Rain ZH v2"
call RENAME_From_To.bat "Glacial Horses V2" "[RANK] Glacial Shores ZH v2"
call RENAME_From_To.bat "Oil Oasis ZH v1" "[RANK] Oil Oasis ZH v1"
call RENAME_From_To.bat "Oil Rampage v6" "[RANK] Oil Rampage ZH v1"
call RENAME_From_To.bat "Planet Coyon V4" "[RANK] Planet Coyon ZH v1"
call RENAME_From_To.bat "Stonehenge ZH v1" "[RANK] Stonehenge ZH v1"
call RENAME_From_To.bat "Tournament Himalaya V5" "[RANK] Tournament Himalaya ZH v1"
call RENAME_From_To.bat "White Hell ZH v1" "[RANK] White Hell ZH v1"
call RENAME_From_To.bat "[RANK] Forgotten Air Battle ZH v6" "[RANK] Forgotten Air Battle ZH v5"
:: 2v2
call RENAME_From_To.bat "Bricks 2v2 ZH v1" "[RANK] Final Departure ZH v1"
call RENAME_From_To.bat "Burning Deadline ZH v1" "[RANK] Burning Deadline ZH v1"
call RENAME_From_To.bat "Combat Encounter" "[RANK] Combat Encounter ZH v1"
call RENAME_From_To.bat "Drowning Horses V1" "[RANK] Drowning Horses ZH v1"
call RENAME_From_To.bat "FallOut ZH v1" "[RANK] Fall Out ZH v1"
call RENAME_From_To.bat "Lion Heart" "[RANK] Lion Heart ZH v1"
call RENAME_From_To.bat "TournamentA v2" "[RANK] Tournament A ZH v1"
call RENAME_From_To.bat "Whispering Woods v1x29" "[RANK] Whispering Woods ZH v1"
:: 3v3
call RENAME_From_To.bat "Coral Islands" "[RANK] Coral Islands ZH v1"
call RENAME_From_To.bat "Defcon Balanced ZH v4" "[RANK] Defcon Balanced ZH v1"
call RENAME_From_To.bat "Icy Frontier ZH v1" "[RANK] Icy Frontier ZH v1"
call RENAME_From_To.bat "Naval Port Reyes [WBC Winner]" "[RANK] Naval Port Reyes ZH v1"
call RENAME_From_To.bat "Philippine Highlands" "[RANK] Philippine Highlands ZH v1"
call RENAME_From_To.bat "Subjugation Mk 14 [WBC Winner]" "[RANK] Subjugation ZH v1"
call RENAME_From_To.bat "Territorial Dispute" "[RANK] Territorial Dispute ZH v1"
:: 4v4
call RENAME_From_To.bat "Dusty Rampage v3" "[RANK] Dusty Rampage ZH v1"
call RENAME_From_To.bat "TT Twister" "[RANK] Twister Land ZH v1"
:: fun
call RENAME_From_To.bat "Mortal Temptation X" "[RANK] Mortal Temptation ZH v1"
